Q1 Create a 1D NumPy array called cost_price containing tge pruce for 3 items [1500,3000,5000]


In [1]:
import numpy as np
a = np.array([1500,3000,5000])


In [2]:
d = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [3]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [4]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [5]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [6]:
print(d)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [7]:
print(d)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [8]:
print(d[:,1])

[15  7  3]


In [16]:
print(d.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [10]:
e = np.random.randint(0,1,5)

In [17]:
arr3 = np.random.randint(0,2,5)

In [18]:
print(arr3)

[0 1 1 0 1]


In [14]:
arr4 = np.arange(0,1,0.25)

In [15]:
arr4

array([0.  , 0.25, 0.5 , 0.75])

In [24]:
arr4 = np.array([[78,85,90],[45,60,55],[88,92,95],[30,50,35],[65,70,75]
        ])

In [25]:
arr4

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [30, 50, 35],
       [65, 70, 75]])

In [27]:
arr4.shape

(5, 3)

In [28]:
arr4.data

In [ ]:
total = arr4.size
total


15

In [38]:
arr4[:,1]

array([85, 60, 92, 50, 70])

In [41]:
arr4[:,2]

array([90, 55, 95, 35, 75])

In [48]:
print(arr4
)

arr4[:2,:2]

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 50 35]
 [65 70 75]]


array([[78, 85],
       [45, 60]])

In [ ]:
print(arr4.mean(axis=0))
print(arr4.mean(axis=1))

[61.2 71.4 70. ]
[84.33333333 53.33333333 91.66666667 38.33333333 70.        ]


In [54]:
print(arr4.mean(axis=0)>=80)

[False False False]


In [55]:
c = np.where(arr4>=50,1,0)

In [56]:
print(c)

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]]
