Q1 Create a 1D NumPy array called cost_price containing tge pruce for 3 items [1500,3000,5000]


In [36]:
import numpy as np
a = np.array([1500,3000,5000])


In [37]:
d = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [38]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [39]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [40]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [41]:
print(d)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [42]:
c= np.arange(0,28)

In [43]:
print(d.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [44]:
print(d)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [45]:
print(d[:,1])

[15  7  3]


In [46]:
print(d.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [47]:
e = np.random.randint(0,1,5)

In [48]:
arr3 = np.random.randint(0,2,5)

In [49]:
print(arr3)

[1 1 0 1 0]


In [50]:
arr4 = np.arange(0,1,0.25)

In [51]:
arr4

array([0.  , 0.25, 0.5 , 0.75])

In [52]:
arr4 = np.array([[78,85,90],[45,60,55],[88,92,95],[30,50,35],[65,70,75]
        ])

In [53]:
arr4

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [30, 50, 35],
       [65, 70, 75]])

In [54]:
arr4.shape

(5, 3)

In [55]:
arr4.data

In [56]:
total = arr4.size
total


15

In [57]:
arr4[:,1]

array([85, 60, 92, 50, 70])

In [58]:
arr4[:,2]

array([90, 55, 95, 35, 75])

In [59]:
print(arr4
)

arr4[:2,:2]

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 50 35]
 [65 70 75]]


array([[78, 85],
       [45, 60]])

In [60]:
print(arr4.mean(axis=0))
print(arr4.mean(axis=1))

[61.2 71.4 70. ]
[84.33333333 53.33333333 91.66666667 38.33333333 70.        ]


In [61]:
print(arr4.mean(axis=0)>=80)

[False False False]


In [62]:
c = np.where(arr4>=50,1,0)

In [63]:
print(c)

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]]


In [64]:
arr5 = arr4.mean(axis=0)

In [65]:
arr5

array([61.2, 71.4, 70. ])

In [66]:
arr6 = np.where(arr5>85,10,np.where(arr5>=70,8,np.where(arr5>=50,6,np.where(arr5<50,0,0))))

In [67]:
arr6

array([6, 8, 8])

In [68]:
arr9 = np.random.randint(120,650,28)

In [69]:
arr12 = arr9.reshape(4,7)

In [70]:
print(arr12.size)
print(arr12.shape)


28
(4, 7)


<b>Q Create a Numpy array elrctricity using np.random.ranint:

In [72]:
arr13 = np.random.randint(120,650,28)
arr14 = arr13.copy().reshape(4,7)
arr14

array([[422, 304, 465, 358, 266, 499, 556],
       [241, 444, 415, 322, 363, 398, 448],
       [336, 159, 590, 341, 549, 505, 317],
       [182, 616, 567, 553, 488, 201, 420]], dtype=int32)

<br>Q Find the average electricity uses per hostel,the maximum usage per hostel and identufy which hostel has the highrst average uses

In [80]:
average = np.mean(arr14,axis=1)
print("The average bill per hostel is :",average)
print("The highest bill per hostel is:",np.max(average,axis=0))

The average bill per hostel is : [410.         375.85714286 399.57142857 432.42857143]
The highest bill per hostel is: 432.42857142857144


<b>Q2 Calculate the total electrucity bill for each hostel and find the highest bill among them.

In [81]:
summ = np.sum(arr14,axis =0)
print("The total bill per day is:",summ)
print("The highest bill per day is:",np.max(summ,axis=0))

The total bill per day is: [1181 1523 2037 1574 1666 1603 1741]
The highest bill per day is: 2037


<br>Q If electricity usages on any day is greater than 550 units , a 20% surcharge is applied on that day’s bill. Calculate the total bill for each day after applying the surcharge if applicable.

In [83]:
Penalized_usage = np.where(arr14>500,arr14+(arr14*20/100),arr14)
print(arr14)
Penalized_usage

[[422 304 465 358 266 499 556]
 [241 444 415 322 363 398 448]
 [336 159 590 341 549 505 317]
 [182 616 567 553 488 201 420]]


array([[422. , 304. , 465. , 358. , 266. , 499. , 667.2],
       [241. , 444. , 415. , 322. , 363. , 398. , 448. ],
       [336. , 159. , 708. , 341. , 658.8, 606. , 317. ],
       [182. , 739.2, 680.4, 663.6, 488. , 201. , 420. ]])

<b> Compare each hostel's daily usage with it's own weekly average Create a boolean matrix where 
<br> the value is True if the daily usage is greater than the weekly average and False otherwise.

In [101]:
Boolean_matrix = np.where(arr14<average[:,None],"True","False")
print(Boolean_matrix)

[['False' 'True' 'False' 'True' 'True' 'False' 'False']
 ['True' 'False' 'False' 'True' 'True' 'False' 'False']
 ['True' 'True' 'False' 'True' 'False' 'False' 'True']
 ['True' 'False' 'False' 'False' 'False' 'True' 'True']]


Q Reshape the elecriticity data into a single row representing weekly usages (Shape: 1X28)

In [95]:
Electricity_data = arr14.reshape(1,28)
print(Electricity_data)

[[422 304 465 358 266 499 556 241 444 415 322 363 398 448 336 159 590 341
  549 505 317 182 616 567 553 488 201 420]]


In [98]:
Electricity_data1 = Electricity_data.copy()
Electricity_data1.reshape(2,14)

array([[422, 304, 465, 358, 266, 499, 556, 241, 444, 415, 322, 363, 398,
        448],
       [336, 159, 590, 341, 549, 505, 317, 182, 616, 567, 553, 488, 201,
        420]], dtype=int32)

Copy vs View <br>
Create ref_backup = Electricity_dataCreate safe_backup = Electricity_data.copy()<br>
Modify one value in the original Electricity_data <br>
Observe which backups change