Q1 Create a 1D NumPy array called cost_price containing tge pruce for 3 items [1500,3000,5000]


In [1]:
import numpy as np
a = np.array([1500,3000,5000])


In [2]:
d = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [3]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [4]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [5]:
d

array([[10, 15,  8, 12],
       [ 5,  7,  4,  6],
       [ 2,  3,  2,  4]])

In [6]:
print(d)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [7]:
c= np.arange(0,28)

In [8]:
print(d.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [9]:
print(d)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [10]:
print(d[:,1])

[15  7  3]


In [11]:
print(d.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [12]:
e = np.random.randint(0,1,5)

In [13]:
arr3 = np.random.randint(0,2,5)

In [14]:
print(arr3)

[0 0 0 0 0]


In [15]:
arr4 = np.arange(0,1,0.25)

In [16]:
arr4

array([0.  , 0.25, 0.5 , 0.75])

In [17]:
arr4 = np.array([[78,85,90],[45,60,55],[88,92,95],[30,50,35],[65,70,75]
        ])

In [18]:
arr4

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [30, 50, 35],
       [65, 70, 75]])

In [19]:
arr4.shape

(5, 3)

In [20]:
arr4.data

In [21]:
total = arr4.size
total


15

In [22]:
arr4[:,1]

array([85, 60, 92, 50, 70])

In [23]:
arr4[:,2]

array([90, 55, 95, 35, 75])

In [24]:
print(arr4
)

arr4[:2,:2]

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 50 35]
 [65 70 75]]


array([[78, 85],
       [45, 60]])

In [25]:
print(arr4.mean(axis=0))
print(arr4.mean(axis=1))

[61.2 71.4 70. ]
[84.33333333 53.33333333 91.66666667 38.33333333 70.        ]


In [26]:
print(arr4.mean(axis=0)>=80)

[False False False]


In [27]:
c = np.where(arr4>=50,1,0)

In [28]:
print(c)

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]]


In [29]:
arr5 = arr4.mean(axis=0)

In [30]:
arr5

array([61.2, 71.4, 70. ])

In [31]:
arr6 = np.where(arr5>85,10,np.where(arr5>=70,8,np.where(arr5>=50,6,np.where(arr5<50,0,0))))

In [32]:
arr6

array([6, 8, 8])

In [33]:
arr9 = np.random.randint(120,650,28)

In [34]:
arr12 = arr9.reshape(4,7)

In [35]:
print(arr12.size)
print(arr12.shape)


28
(4, 7)


<b>Q Create a Numpy array elrctricity using np.random.ranint:

In [36]:
arr13 = np.random.randint(120,650,28)
arr14 = arr13.copy().reshape(4,7)
arr14

array([[458, 517, 585, 552, 555, 135, 381],
       [374, 306, 474, 524, 289, 313, 325],
       [556, 405, 165, 143, 412, 584, 306],
       [486, 325, 309, 146, 410, 444, 391]], dtype=int32)

<br>Q Find the average electricity uses per hostel,the maximum usage per hostel and identufy which hostel has the highrst average uses

In [37]:
average = np.mean(arr14,axis=1)
print("The average bill per hostel is :",average)
print("The highest bill per hostel is:",np.max(average,axis=0))

The average bill per hostel is : [454.71428571 372.14285714 367.28571429 358.71428571]
The highest bill per hostel is: 454.7142857142857


<b>Q2 Calculate the total electrucity bill for each hostel and find the highest bill among them.

In [38]:
summ = np.sum(arr14,axis =0)
print("The total bill per day is:",summ)
print("The highest bill per day is:",np.max(summ,axis=0))

The total bill per day is: [1874 1553 1533 1365 1666 1476 1403]
The highest bill per day is: 1874


<br>Q If electricity usages on any day is greater than 550 units , a 20% surcharge is applied on that day’s bill. Calculate the total bill for each day after applying the surcharge if applicable.

In [39]:
Penalized_usage = np.where(arr14>500,arr14+(arr14*20/100),arr14)
print(arr14)
Penalized_usage

[[458 517 585 552 555 135 381]
 [374 306 474 524 289 313 325]
 [556 405 165 143 412 584 306]
 [486 325 309 146 410 444 391]]


array([[458. , 620.4, 702. , 662.4, 666. , 135. , 381. ],
       [374. , 306. , 474. , 628.8, 289. , 313. , 325. ],
       [667.2, 405. , 165. , 143. , 412. , 700.8, 306. ],
       [486. , 325. , 309. , 146. , 410. , 444. , 391. ]])

<b> Compare each hostel's daily usage with it's own weekly average Create a boolean matrix where 
<br> the value is True if the daily usage is greater than the weekly average and False otherwise.

In [40]:
Boolean_matrix = np.where(arr14<average[:,None],"True","False")
print(Boolean_matrix)

[['False' 'False' 'False' 'False' 'False' 'True' 'True']
 ['False' 'True' 'False' 'False' 'True' 'True' 'True']
 ['False' 'False' 'True' 'True' 'False' 'False' 'True']
 ['False' 'True' 'True' 'True' 'False' 'False' 'False']]


Q Reshape the elecriticity data into a single row representing weekly usages (Shape: 1X28)

In [41]:
Electricity_data = arr14.reshape(1,28)
print(Electricity_data)

[[458 517 585 552 555 135 381 374 306 474 524 289 313 325 556 405 165 143
  412 584 306 486 325 309 146 410 444 391]]


In [42]:
Electricity_data1 = Electricity_data.copy()
Electricity_data1.reshape(2,14)

array([[458, 517, 585, 552, 555, 135, 381, 374, 306, 474, 524, 289, 313,
        325],
       [556, 405, 165, 143, 412, 584, 306, 486, 325, 309, 146, 410, 444,
        391]], dtype=int32)

Copy vs View <br>
Create ref_backup = Electricity_dataCreate safe_backup = Electricity_data.copy()<br>
Modify one value in the original Electricity_data <br>
Observe which backups change