# Numpy

#### Creating the array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,4,5],dtype=np.int32)

In [3]:
print(arr)

[1 2 4 5]


In [4]:
arr

array([1, 2, 4, 5], dtype=int32)

##### Printing the type of array

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


##### 2d dimensional array

In [6]:
c = np.array([[1,2,4],[4,5,6],[4,5,7]])

In [7]:
print(c)

[[1 2 4]
 [4 5 6]
 [4 5 7]]


#### Some functions of numpy

In [8]:
n = np.zeros(6)

In [9]:
n

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Range of number

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Even linespace

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Two dimensional array

In [15]:
mat = np.array([[1,2,4],[4,5,6],[4,3,6]])

In [16]:
print(mat[1]) #This will print the column
print(mat[0,1])

[4 5 6]
2


#### Copying the array

##### Not safe method

In [17]:
arr2 = np.array([1,2,3])
arr3 = arr2 #this logic is not safe
arr3[0] = 99
print(arr2)

[99  2  3]


##### Safe method

In [18]:
arr2 = np.array([1,2,4])
arr3 = arr2.copy()
print(arr2)
arr3

[1 2 4]


array([1, 2, 4])

#### Basic array operations(vector operations)

In [19]:
a = np.array([1,3,4,5])
b = np.array([3,4,5,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 4  7  9 10]
[-2 -1 -1  0]
[ 3 12 20 25]
[0.33333333 0.75       0.8        1.        ]


Scaler Options

In [20]:
print(a+10)
print(a*2)

[11 13 14 15]
[ 2  6  8 10]


#### Universal Funtions

In [21]:
arr = np.array([1,2,3,5])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))  #standard devation

[1.         1.41421356 1.73205081 2.23606798]
[0.         0.69314718 1.09861229 1.60943791]
[  2.71828183   7.3890561   20.08553692 148.4131591 ]
5
1
2.75
11
1.479019945774904


#### Boolean Indexing

In [22]:
arr = np.array([10,20,30,40])
print(arr[arr>25])
print(arr>25)

[30 40]
[False False  True  True]


#### Element wise Multiplication

a = [2 3      b = [1 0                     
     4 5]          2 3  ]

    c = A*B(python) corrosponds to = c = a b (math)
<b>Note: <b> The python <b>* <b>operator does not sum the results. It maintains the shape

### Broadcasting
Broadcasting describes how Numpy treats arrays with different shapes during arithemetics operations. The smaller array is 'broadcast' (stretched )across the larger array so that they have compatible shapes.<br>
##### How numpy checks for Broadcasting(Right-to-Left Rule):
<br>
When operating on two arrays,Numpy compares their shapes elemenet wise.It starts with the trailing(rightmost) dimension and works its way to left
Two dimensions are compatible:

##### Broadcasting Rule 

<b>NumPy automatically expandas smaller arrays to match the shape of larger arrays when performing operations. This is called broadcasting.</b>

In [23]:
arr = np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [24]:
mat = np.array([[1,2,3],[2,4,5]])
print(mat+10)

[[11 12 13]
 [12 14 15]]


In [25]:
row = np.array([1,2,3])
print(row+mat)

[[2 4 6]
 [3 6 8]]


#### Matrix Multiplication

In [26]:
A = np.array( [[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
# we have to use the dot function otherwise numpy will multiply it as element wise 
print(np.dot(A,B))


[[19 22]
 [43 50]]


In [27]:
print(np.transpose(np.dot(A,B)))

[[19 43]
 [22 50]]


#### Random Module

In [28]:
np.random.rand(5) 
#It will give me random value array till asked

array([0.72131594, 0.51863318, 0.96308875, 0.62910673, 0.64542086])

In [29]:
np.random.rand(3,3)  
# random array with size 3X3

array([[0.39470978, 0.05494459, 0.78446839],
       [0.25045815, 0.53774256, 0.70952515],
       [0.49602898, 0.94227177, 0.50919851]])

In [30]:
np.random.randint(1,100,10)  
#It starts from 1 to 100 with a array size of 10 like just 10 values

array([86, 17, 21, 13, 29,  5, 37, 71, 84, 73], dtype=int32)

#### Reshaping Array

In [31]:
arr5 = np.arange(12)
print(arr5.reshape(4,3))
arr6 = arr5.reshape(4,3)
#The first line will make a 1-d array of 12 and the reshape will convert it into a 
# 3X4 size

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### Axis operations

In [32]:
print(np.sum(arr6))

66


In [33]:
print(np.sum(arr6, axis=0))  #Column -wise

[18 22 26]


In [34]:
print(np.sum(arr6,axis=1)) #row wise

[ 3 12 21 30]


#### Where in numpy

In [35]:
arr = np.array([10,-5,20,-3,15])

In [36]:
result = np.where(arr<0,0,arr)
#argument,return it to whatever you want,The other value in this case the original value
print(result)

[10  0 20  0 15]


In [37]:
arr = np.arange(1,6)

In [38]:
result = np.where(arr%2!=0,-1,arr)
print(result)

[-1  2 -1  4 -1]


In [39]:
marks = np.random.randint(20,100,10)
print(marks)

[64 82 94 99 79 39 80 64 95 53]


In [40]:
result = np.where(marks>=50,1,0)
print(result)

[1 1 1 1 1 0 1 1 1 1]


In [41]:
num = np.arange(10,60,10)

In [42]:
mean_val = num.mean()
result = np.where(num>mean_val,mean_val,num)
print(result)

[10. 20. 30. 30. 30.]


In [43]:
mat = np.random.randint(10,100,9)
c = mat.reshape(3,3)
print(c)

[[71 86 35]
 [30 46 14]
 [43 36 10]]


##### Where in 2-d array

In [44]:
result = np.where(c>50,1,0)
print(result)

[[1 1 0]
 [0 0 0]
 [0 0 0]]
