<a href="https://colab.research.google.com/github/harsh4214/Foundation-of-Machine-Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas
import torch
import numpy
import matplotlib.pyplot as plt


In [2]:
#vector
vector = torch.tensor([1,2,3])
print(vector.shape)
vector.ndim

torch.Size([3])


1

In [3]:
#matrix

MATRIX = torch.tensor([[1,2,3],[4,5,6],[6,7,8]])
MATRIX,MATRIX.size()

(tensor([[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]),
 torch.Size([3, 3]))

In [4]:
#tensor

Tensor = torch.tensor([[[1,2,3],[1,2,3]]])
Tensor.shape


torch.Size([1, 2, 3])

In [5]:
  #random tensors
#i
image_tensors = torch.rand(size=(244,244,3)) #height,width,colour_channels
image_tensors

tensor([[[0.2175, 0.0189, 0.8460],
         [0.9241, 0.4150, 0.8966],
         [0.1061, 0.7634, 0.5376],
         ...,
         [0.7839, 0.6006, 0.9240],
         [0.1123, 0.9665, 0.1058],
         [0.6975, 0.0818, 0.1087]],

        [[0.3896, 0.5585, 0.1486],
         [0.7383, 0.1220, 0.9453],
         [0.5568, 0.8239, 0.7310],
         ...,
         [0.4860, 0.6971, 0.8179],
         [0.9082, 0.2516, 0.0834],
         [0.6626, 0.1163, 0.2465]],

        [[0.8064, 0.2684, 0.6135],
         [0.7123, 0.7940, 0.3678],
         [0.2886, 0.7655, 0.1812],
         ...,
         [0.3916, 0.5322, 0.3213],
         [0.5589, 0.7012, 0.9196],
         [0.7602, 0.6957, 0.6598]],

        ...,

        [[0.7223, 0.4555, 0.2547],
         [0.6907, 0.5815, 0.8677],
         [0.8790, 0.0441, 0.6733],
         ...,
         [0.2609, 0.8460, 0.1599],
         [0.0979, 0.5561, 0.7189],
         [0.0114, 0.3971, 0.5139]],

        [[0.7385, 0.9325, 0.9498],
         [0.2525, 0.9738, 0.0935],
         [0.

In [6]:
image_tensors.ndim,image_tensors.shape

(3, torch.Size([244, 244, 3]))

In [7]:
#zeros tensors
zeros = torch.zeros(size=(2,2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [8]:
#ones tensors
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
#Data at tensor
ones.dtype

torch.float32

In [10]:
intt = torch.rand(size=(2,3),device=None,dtype=torch.float16)
intt

tensor([[0.9341, 0.9404, 0.3984],
        [0.7803, 0.9282, 0.6899]], dtype=torch.float16)

# Three important part in creating tensors are
####dtype= what data type is used torch.float32
####device= what device is it on cpu or cuda
####require_grad= tracks the gradient either True or False

In [11]:
#Changing data type of tensor
float_32tensor = torch.rand(2,3,dtype=torch.float64)
print(float_32tensor)
float_16tensor = float_32tensor.type(torch.float16)
print(float_16tensor)

tensor([[0.9785, 0.7272, 0.6188],
        [0.8326, 0.2839, 0.5377]], dtype=torch.float64)
tensor([[0.9785, 0.7271, 0.6187],
        [0.8325, 0.2839, 0.5376]], dtype=torch.float16)


<h2>Manipulating Tensors (tensor operations)</h2>

<p>Tensor operations include:</p>

<ul>
    <li>Addition</li>
    <li>Subtraction</li>
    <li>Multiplication (element-wise)</li>
    <li>Division</li>
    <li>Matrix multiplication</li>
</ul>



In [12]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [13]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [14]:
tensor

tensor([1, 2, 3])

In [15]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [16]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [17]:
#Matrix multiplication

tensor1 = torch.tensor([1,2,4])
tenson2 = torch.tensor([2,4,6])
tensor3 = tensor1.matmul(tenson2)
print(tensor3)
print(torch.matmul(tensor1,tenson2))

# Matrix multiplcation using @

print(tensor1@tenson2)

#torch.mm is same as torch.matmul()

tensor(34)
tensor(34)
tensor(34)


<h2>Mean, Median, Mode, Max, Sum, etc (tensor aggrigation)</h2>

In [18]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [19]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [20]:
x.type(torch.float32).mean()

tensor(46.)

In [21]:
y = torch.arange(1,10,3 ,dtype=torch.float32)
y.max(),torch.max(y)


(tensor(7.), tensor(7.))

In [22]:
#This is to find the mean

y.mean()

tensor(4.)

<h2>Find the argumental mean </h2>
<p> Mtlv just index value</p>

In [23]:
y


tensor([1., 4., 7.])

In [24]:
y.argmin()

tensor(0)

In [25]:
y.argmax()

tensor(2)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [26]:
stack1 = torch.tensor([1,2,3])
stack2 = torch.tensor([4,5,6])
stack3 = torch.stack([stack1,stack2],dim=1) #by default the dimension is 0
print(stack3.size())
print(stack3.ndim)



torch.Size([3, 2])
2


In [27]:
squeeze1 = torch.arange(1,20,5)
squeeze1

tensor([ 1,  6, 11, 16])

In [28]:
squeeze1.reshape(2,2)

tensor([[ 1,  6],
        [11, 16]])

In [29]:
squeeze1.squeeze()

tensor([ 1,  6, 11, 16])

#### Using Gpu

In [30]:
device = "cuda" if torch.cuda.is_available() else "cpu"  #this make sure that if a computer has a gpu it should
# use it else use the cpu

In [31]:
device

'cuda'

### Moving tensors to cuda using the ".to" method

In [37]:
t1 = torch.tensor([1,2,4])
gpu_tensor = tensor.to("cuda")

In [34]:
gpu_tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [40]:
## since numpy only works with the cpu so in order to use numpy we have to use cpu
tenosr_on_cpu = gpu_tensor.cpu().numpy()

In [44]:
## Exercise 1
t1 = torch.rand(size=(7,7))
t2 = torch.rand(size=(1,7))
mul = torch.matmul(t1,t2.T)  #the t function is used to do the transpose meaning row in column and column into row so 1,7 becomes 7,1
print(mul)

tensor([[1.7055],
        [1.7431],
        [1.4613],
        [0.9573],
        [1.3189],
        [0.9549],
        [1.5577]])
